### ISSUE TITLE
User Auth (pre-CSS)

### ISSUE THREAD

**Issue by gorterd** [robokitten007/slashsmart#2]
Awesome work, Wen! Functionality is on point, so not too much to revise!

- Note: I'll hold off on all CSS feedback for now (whenever you resubmit the card for review, just make sure to complete the styling first, now that we've had the CSS lecture). 
  - Be sure to also include splash content when you resubmit. You should clone enough of the splash content to fill the whole page vertically, before getting to the footer. 
  - Speaking of the footer, you'll want to have one, but you don't want deadlinks (e.g. no 'About' link to an about page that doesn't exist). So you'll want to replace the content with custom text content. For example, you could treat it as a mini-resume and list technologies, languages you know, etc.
- [x] You'll want to have the signup form start with a single name input, then when you type into it, the email / password inputs should show up (like Splitwise)

**Comment by gorterd** [comment]
Nice work! Here's my auth feedback, with styling

- [x] Sign Up: I only see a white color background on Splitwise; so I'd remove the image background. 
  - [x] Also, I'd make sure the splitwise logo is to the left of the input (match the layout on Splitwise), and that it doesn't include the 'Splitwise' white text.
- [x] Login: You'll want to give the form box a box shadow. 
  - [x] On my screen, the footer doesn't hit the bottom of the page on the login page. One option is to give the primary component a minimum height of 100vh (full screen height -- [read more here](https://css-tricks.com/fun-viewport-units/)) minus the height of the footer (you could use [calc()](https://developer.mozilla.org/en-US/docs/Web/CSS/calc())).
  - I'd also recommend the 'Log in' header text, and label text, matches Splitwise more closely (decrease font weight)
- [x] The session error messages should be in a red box with white text, like Splitwise.

**Comment by robokitten007** [comment]
I've fixed most of your comments. As to the footer, I am not quite sure what you mean, could you give me a screenshot of how it looks like on your end?
thank you!

**Comment by robokitten007** [comment]
fixed footer gap on login page
